name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Download Inno Setup
      run: |
        $url = "https://files.jrsoftware.org/is/6/innosetup-6.2.2.exe"
        $output = "innosetup.exe"
        Invoke-WebRequest -Uri $url -OutFile $output
        Start-Process -FilePath $output -ArgumentList "/VERYSILENT /SUPPRESSMSGBOXES" -Wait
      
    - name: Compile Installer
      run: |
        $version = (Get-Content version.json | ConvertFrom-Json).version
        $env:APP_VERSION = $version
        & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" installer.iss
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ github.run_number }}
        name: Release v${{ github.run_number }}
        files: |
          dist/SwatchonChat-Setup-*.exe
          dist/SwatchonChat-*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 