name: Build and Release Components

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Zip core
        run: zip -r core.zip core

      - name: Zip ui
        run: zip -r ui.zip ui

      - name: Zip services
        run: zip -r services.zip services

      - name: Generate components.json
        run: python scripts/generate_components_json.py ${{ github.run_number }}

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
          files: |
            core.zip
            ui.zip
            services.zip
            components/components.json
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }} 